name: chatbi

services:
  postgres:
    restart: always
    image: postgres:15-alpine
    container_name: chatbi-postgres
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: chatbi
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: chatbi

    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  redis:
    restart: always
    image: redis:7-alpine
    container_name: chatbi-redis
    ports:
      - 16379:6379

  qdrant:
    image: qdrant/qdrant:v1.12.1
    container_name: chatbi-qdrant
    restart: always
    ports:
      - 6333:6333  # HTTP API
      - 6334:6334  # gRPC API
    volumes:
      - ./qdrant/storage:/qdrant/storage
      - ./qdrant/snapshots:/qdrant/snapshots
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:6333/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
